name: Deploy to server

on: 
  - push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Workin dir
          run: ls -al

        - name: Action
          run: actions/checkout@v4

        - name: Workin dir after action
          run: ls -al
    
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest    
    steps:
        - name: Hola mundo 2
          run: echo "Hola mundo 2 ${{ github.ref }}"