name: Deploy to server

on: 
  - push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Workin dir
          id: step_1
          run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

        - name: Obtener mensaje
          run: echo "${{ steps.step_1.outputs.my_variable }}"
    
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest    
    steps:
        - name: Hola mundo 2
          run: echo "Hola mundo 2 ${{ github.ref }}"