name: Deploy to server

on: 
  - push

jobs:
  first-job:
    runs-on: ubuntu-latest

    outputs:
      salida: hola      

    steps:
        - name: Workin dir
          id: step_1
          run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

        - name: Obtener mensaje
          run: echo "${{ steps.step_1.outputs.my_variable }}"
    
  second-job:
    needs: first-job
    runs-on: ubuntu-latest    

    env:
      SALIDA: ${{ needs.first-job.outputs.salida }}
    steps:
        - name: Hola mundo 2
          run: echo "$SALIDA"